# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  languageserver = {
    pname = "languageserver";
    version = "1e71561a41ef59126273f16bbb466c0b30a2aa64";
    src = fetchgit {
      url = "https://github.com/REditorSupport/languageserver";
      rev = "1e71561a41ef59126273f16bbb466c0b30a2aa64";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-bxPbthcEzn3tQW9cCZmw5fh5veAQc6TxRaXLfM9DgW8=";
    };
    date = "2023-04-25";
  };
}
